services:
  php:
    container_name: endpoint
    image: mckillem/endpoint
    build: build/php
    volumes:
      - ../:/var/www/html
    ports:
      - "8091:80"
    environment:
      - NETTE_DEBUG=1
#      - COMPOSER_AUTH=${COMPOSER_AUTH}
    links:
      - database

  database:
    container_name: endpoint_db
    image: mckillem/endpoint_db
    build: build/database
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: endpoint
    volumes:
      - ./build/database/01_create.sql:/docker-entrypoint-initdb.d/01_create.sql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8090:80"
    environment:
      - PMA_HOST=database
      - PMA_USER=test
      - PMA_PASSWORD=test